<footer class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h3 class="mt-0 mb-1">Contact Information</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-6">
            <p class="mt-0 mb-1"><strong>CorpU</strong></p>
            <p class="mt-0 mb-1">999 Riversdale Road<br>Hawthorn, VIC 3122</p>
        </div>
        <div class="col-12 col-sm-6">
            <p class="mt-0 mb-1">Tel: 0439998888</p>
            <p class="mt-0 mb-1">Email: <a href="mailto:info@corpu.edu">info@corpu.edu</a></p>
            <p class="mt-0 mb-1">&#169; CorpU 2023</p>
        </div>
    </div>
</footer>